import {VerticalBox, HorizontalBox, TabWidget, Button, TextEdit, ListView, ComboBox, LineEdit, AboutSlint} from "std-widgets.slint";
import {EQCanvas, EQCanvasLogic,EQCurveData, EQGraphManager, DraggableLogic, FilterType} from "eq_canvas.slint";
import {EQ-CONTROL-SECTION-MANAGER, EQ_CONTROL_SECTION, FILTER-SELECTION-POP-UP} from "eq_control_section.slint";
// global exports
export {EQGraphManager, EQCanvasLogic, DraggableLogic}


struct Filter {
    id: int,
    selected: { str: string,type: FilterType},
}

export component AppWindow inherits Window {

    preferred-width: EQGraphManager.eq_graph_width;
    height: 670px;
    // width: EQGraphManager.eq_graph_width;
    // height: EQGraphManager.eq_graph_height;
    in property <[string]> curve_data;

    Rectangle { width: parent.width; height: parent.height; background: #353c51;}
    ta := TouchArea { fs := FocusScope {} clicked => {fs.focus()}}
    outer_layer := VerticalLayout { 
        // width: parent.width;
        // alignment: start;    
        
        width: EQGraphManager.eq_graph_width;
        height: parent.height;
        alignment: start;
        // spacing: 20px;
        // DEBUG here
        HorizontalLayout { height: 90px; width: EQGraphManager.eq_graph_width;   
            alignment:center;
            Text {vertical-alignment: center; horizontal-alignment: center; text: "TheEQfromBelow"; font-family: "CodeNewRoman Nerd Font"; font-size: 60px;}
        }
        
        // EQ CANVAS SECTION
        Rectangle { 
            width: parent.width; 
            height: EQGraphManager.eq_graph_height;       
            eq_canvas := EQCanvas {x: 0; y: 0;}
        }

        eq_control := EQ-CONTROL-SECTION {
            width: parent.width;
            height: 200px;
        }
        AboutSlint {
            width: parent.width;
            height: 50px;
        }
    }

    // if EQ-CONTROL-SECTION-MANAGER.show_filter_type_selection: 
    //         FILTER-SELECTION-POP-UP {
    //             // x: EQ-CONTROL-SECTION-MANAGER.place_filter_selection_x - self.absolute-position.x;
    //             // y: EQ-CONTROL-SECTION-MANAGER.place_filter_selection_y - self.absolute-position.y;
    //     }
}
